### ISSUE TITLE
NO WALLETS?

### ISSUE THREAD

**Issue by diveyez** [AppleByteMe/AppleByte#5]
I cannot find any working wallets for your cryptocurrency, please advise!

**Comment by AppleByteMe** [comment]
All our wallets are available for download here: https://www.artbyte.me/get-started/

**Comment by diveyez** [comment]
Unacceptable Wallets Mates. We need a solution to the downloading massive blockchain problem. Yes, the applications are great. However having to sync every time the wallet is opened is a massive pain. See others for examples.

**Comment by diveyez** [comment]
Please port to iOS when you fix the bugs on android. 
PSN: Less instability on iOS ;) Strongly suggest it.

**Comment by fogoat** [comment]
The blockchain is here: http://forum.artbyte.me/topic/5141-detailed-instructions-for-downloading-an-artbyte-wallet/

Many desktop wallets operate the same way. Electrum exists as an alternative to full node wallets, but light wallets are a security issue to the end user since someone else knowing your IP means you could be a victim of hacks more easily. ArtByte blockchain syncs quickly for me, so I think maybe you are criticizing ArtByte blockchain without really using.

Anyway, please close issue they gave you a link for downloading the wallet.
